{
    "name": "Medical Store Management",
    "summary": "This is a medical store management system.",
    "description": "This module includes medicines and other information.",
    "version": "15.0.0.1.0",
    "category": "Management",
    "website": "https://www.aktivsoftware.com",
    "depends": [],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_sequence_data.xml",
        "data/ir_sequence_lot.xml",
        "views/medicine_information_view.xml",
        "views/health_symptoms_view.xml",
        "views/medicine_symptoms_information_view.xml",
        "views/medicine_lot_view.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
    "license": "LGPL-3",
}
