{
    "name": "Library Management",
    "summary": "This is a library management system.",
    "description": "This module includes books and other information related to library.",
    "version": "15.0.0.1.0",
    "category": "Management",
    "website": "https://www.aktivsoftware.com",
    "depends": ["mail", "sale"],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_sequence_book.xml",
        "data/mail_template_data.xml",
        "data/action_book_return.xml",
        "data/return_reminder_mail_template.xml",
        "data/return_reminder_cron.xml",
        "views/book_author_view.xml",
        "views/book_type_view.xml",
        "views/book_details_view.xml",
        "views/register_books_view.xml",
        "views/register_date_view.xml",
        "views/issue_book_view.xml",
        "views/sale_order_inherited_view.xml",
        "views/res_partner_inherited_view.xml",
        "views/res_partner_author_inherited_view.xml",
        "wizards/issue_wizard_view.xml",
        "wizards/return_book_wizard_view.xml",
        "wizards/context_wizard_view.xml",
        "report/issue_book_report.xml",
        "report/issue_book_report_template.xml",
        "report/return_book_report.xml",
        "report/return_book_report_template.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
    "license": "LGPL-3",
}
